### ISSUE TITLE
Error: unable to determine transport target for "pino-pretty"

### ISSUE THREAD

**Issue by Naozumi520** [AHGGG/poe-node-api#14]
__dirname: /Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist
Error: unable to determine transport target for "pino-pretty"
    at fixTarget (/Users/naozumi/Desktop/maple/node_modules/pino/lib/transport.js:140:13)
    at transport (/Users/naozumi/Desktop/maple/node_modules/pino/lib/transport.js:114:22)
    at normalizeArgs (/Users/naozumi/Desktop/maple/node_modules/pino/lib/tools.js:311:16)
    at Function.pino (/Users/naozumi/Desktop/maple/node_modules/pino/pino.js:87:28)
    at new PoeClient (file:///Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist/PoeClient.js:71:28)
    at module.exports (/Users/naozumi/Desktop/maple/src/messages/react.js:5:22)

**Comment by Naozumi520** [comment]
I fixed it by following [this](https://stackoverflow.com/questions/71938587/unable-to-determine-transport-target-for-pino-pretty), how ever, I got a new issue:

TypeError: Cannot read properties of undefined (reading 'viewer')
    at PoeClient.getNextData (file:///Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist/PoeClient.js:391:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PoeClient.updateAllBotInfo (file:///Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist/PoeClient.js:616:9)
    at async PoeClient.init (file:///Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist/PoeClient.js:168:13)
    at async module.exports (/Users/naozumi/Desktop/maple/src/messages/react.js:6:5)

**Comment by AHGGG** [comment]
The viewer data structure has changed, and I'll fix it.

**Comment by AHGGG** [comment]
> I fixed it by following [this](https://stackoverflow.com/questions/71938587/unable-to-determine-transport-target-for-pino-pretty), how ever, I got a new issue:
> 
> TypeError: Cannot read properties of undefined (reading 'viewer') at PoeClient.getNextData (file:///Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist/PoeClient.js:391:50) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async PoeClient.updateAllBotInfo (file:///Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist/PoeClient.js:616:9) at async PoeClient.init (file:///Users/naozumi/Desktop/maple/node_modules/poe-node-api/dist/PoeClient.js:168:13) at async module.exports (/Users/naozumi/Desktop/maple/src/messages/react.js:6:5)

Try version: 0.0.8-rc1

**Comment by Naozumi520** [comment]
Yes it's working! :D
